blank_issues_enabled: true
contact_links:
  - name: Ensign College Helpdesk
    url: https://www.ensign.edu/helpdesk
    about: Please ask questions here.
  - name: Web Request Changes
    url: https://form.asana.com/?k=tUK4Ws5FxVVy6UisB4FAXg&d=1199410528038035
    about: Request changes to site
